use std::default;
use std::convert;

#[derive(Debug,PartialEq)]
pub(crate) struct CharsetData {
    pub(crate) preferred_name: &'static str,
    pub(crate) name: &'static str,
    pub(crate) names: &'static [&'static str],
}

pub(crate) const CD: &'static [CharsetData; 258] = &[
    CharsetData { preferred_name: "US-ASCII", name: "US-ASCII", names: &["iso-ir-6", "ANSI_X3.4-1968", "ANSI_X3.4-1986", "ISO_646.irv:1991", "ISO646-US", "US-ASCII", "us", "IBM367", "cp367", "csASCII"] },
    CharsetData { preferred_name: "ISO-8859-1", name: "ISO_8859-1:1987", names: &["iso-ir-100", "ISO_8859-1", "ISO-8859-1", "latin1", "l1", "IBM819", "CP819", "csISOLatin1"] },
    CharsetData { preferred_name: "ISO-8859-2", name: "ISO_8859-2:1987", names: &["iso-ir-101", "ISO_8859-2", "ISO-8859-2", "latin2", "l2", "csISOLatin2"] },
    CharsetData { preferred_name: "ISO-8859-3", name: "ISO_8859-3:1988", names: &["iso-ir-109", "ISO_8859-3", "ISO-8859-3", "latin3", "l3", "csISOLatin3"] },
    CharsetData { preferred_name: "ISO-8859-4", name: "ISO_8859-4:1988", names: &["iso-ir-110", "ISO_8859-4", "ISO-8859-4", "latin4", "l4", "csISOLatin4"] },
    CharsetData { preferred_name: "ISO-8859-5", name: "ISO_8859-5:1988", names: &["iso-ir-144", "ISO_8859-5", "ISO-8859-5", "cyrillic", "csISOLatinCyrillic"] },
    CharsetData { preferred_name: "ISO-8859-6", name: "ISO_8859-6:1987", names: &["iso-ir-127", "ISO_8859-6", "ISO-8859-6", "ECMA-114", "ASMO-708", "arabic", "csISOLatinArabic"] },
    CharsetData { preferred_name: "ISO-8859-7", name: "ISO_8859-7:1987", names: &["iso-ir-126", "ISO_8859-7", "ISO-8859-7", "ELOT_928", "ECMA-118", "greek", "greek8", "csISOLatinGreek"] },
    CharsetData { preferred_name: "ISO-8859-8", name: "ISO_8859-8:1988", names: &["iso-ir-138", "ISO_8859-8", "ISO-8859-8", "hebrew", "csISOLatinHebrew"] },
    CharsetData { preferred_name: "ISO-8859-9", name: "ISO_8859-9:1989", names: &["iso-ir-148", "ISO_8859-9", "ISO-8859-9", "latin5", "l5", "csISOLatin5"] },
    CharsetData { preferred_name: "ISO-8859-10", name: "ISO-8859-10", names: &["iso-ir-157", "l6", "ISO_8859-10:1992", "csISOLatin6", "latin6"] },
    CharsetData { preferred_name: "", name: "ISO_6937-2-add", names: &["iso-ir-142", "csISOTextComm"] },
    CharsetData { preferred_name: "", name: "JIS_X0201", names: &["X0201", "csHalfWidthKatakana"] },
    CharsetData { preferred_name: "", name: "JIS_Encoding", names: &["csJISEncoding"] },
    CharsetData { preferred_name: "Shift_JIS", name: "Shift_JIS", names: &["MS_Kanji", "csShiftJIS"] },
    CharsetData { preferred_name: "EUC-JP", name: "Extended_UNIX_Code_Packed_Format_for_Japanese", names: &["csEUCPkdFmtJapanese", "EUC-JP"] },
    CharsetData { preferred_name: "", name: "Extended_UNIX_Code_Fixed_Width_for_Japanese", names: &["csEUCFixWidJapanese"] },
    CharsetData { preferred_name: "", name: "BS_4730", names: &["iso-ir-4", "ISO646-GB", "gb", "uk", "csISO4UnitedKingdom"] },
    CharsetData { preferred_name: "", name: "SEN_850200_C", names: &["iso-ir-11", "ISO646-SE2", "se2", "csISO11SwedishForNames"] },
    CharsetData { preferred_name: "", name: "IT", names: &["iso-ir-15", "ISO646-IT", "csISO15Italian"] },
    CharsetData { preferred_name: "", name: "ES", names: &["iso-ir-17", "ISO646-ES", "csISO17Spanish"] },
    CharsetData { preferred_name: "", name: "DIN_66003", names: &["iso-ir-21", "de", "ISO646-DE", "csISO21German"] },
    CharsetData { preferred_name: "", name: "NS_4551-1", names: &["iso-ir-60", "ISO646-NO", "no", "csISO60DanishNorwegian", "csISO60Norwegian1"] },
    CharsetData { preferred_name: "", name: "NF_Z_62-010", names: &["iso-ir-69", "ISO646-FR", "fr", "csISO69French"] },
    CharsetData { preferred_name: "", name: "ISO-10646-UTF-1", names: &["csISO10646UTF1"] },
    CharsetData { preferred_name: "", name: "ISO_646.basic:1983", names: &["ref", "csISO646basic1983"] },
    CharsetData { preferred_name: "", name: "INVARIANT", names: &["csINVARIANT"] },
    CharsetData { preferred_name: "", name: "ISO_646.irv:1983", names: &["iso-ir-2", "irv", "csISO2IntlRefVersion"] },
    CharsetData { preferred_name: "", name: "NATS-SEFI", names: &["iso-ir-8-1", "csNATSSEFI"] },
    CharsetData { preferred_name: "", name: "NATS-SEFI-ADD", names: &["iso-ir-8-2", "csNATSSEFIADD"] },
    CharsetData { preferred_name: "", name: "NATS-DANO", names: &["iso-ir-9-1", "csNATSDANO"] },
    CharsetData { preferred_name: "", name: "NATS-DANO-ADD", names: &["iso-ir-9-2", "csNATSDANOADD"] },
    CharsetData { preferred_name: "", name: "SEN_850200_B", names: &["iso-ir-10", "FI", "ISO646-FI", "ISO646-SE", "se", "csISO10Swedish"] },
    CharsetData { preferred_name: "", name: "KS_C_5601-1987", names: &["iso-ir-149", "KS_C_5601-1989", "KSC_5601", "korean", "csKSC56011987"] },
    CharsetData { preferred_name: "ISO-2022-KR", name: "ISO-2022-KR", names: &["csISO2022KR"] },
    CharsetData { preferred_name: "EUC-KR", name: "EUC-KR", names: &["csEUCKR"] },
    CharsetData { preferred_name: "ISO-2022-JP", name: "ISO-2022-JP", names: &["csISO2022JP"] },
    CharsetData { preferred_name: "ISO-2022-JP-2", name: "ISO-2022-JP-2", names: &["csISO2022JP2"] },
    CharsetData { preferred_name: "", name: "JIS_C6220-1969-jp", names: &["JIS_C6220-1969", "iso-ir-13", "katakana", "x0201-7", "csISO13JISC6220jp"] },
    CharsetData { preferred_name: "", name: "JIS_C6220-1969-ro", names: &["iso-ir-14", "jp", "ISO646-JP", "csISO14JISC6220ro"] },
    CharsetData { preferred_name: "", name: "PT", names: &["iso-ir-16", "ISO646-PT", "csISO16Portuguese"] },
    CharsetData { preferred_name: "", name: "greek7-old", names: &["iso-ir-18", "csISO18Greek7Old"] },
    CharsetData { preferred_name: "", name: "latin-greek", names: &["iso-ir-19", "csISO19LatinGreek"] },
    CharsetData { preferred_name: "", name: "NF_Z_62-010_(1973)", names: &["iso-ir-25", "ISO646-FR1", "csISO25French"] },
    CharsetData { preferred_name: "", name: "Latin-greek-1", names: &["iso-ir-27", "csISO27LatinGreek1"] },
    CharsetData { preferred_name: "", name: "ISO_5427", names: &["iso-ir-37", "csISO5427Cyrillic"] },
    CharsetData { preferred_name: "", name: "JIS_C6226-1978", names: &["iso-ir-42", "csISO42JISC62261978"] },
    CharsetData { preferred_name: "", name: "BS_viewdata", names: &["iso-ir-47", "csISO47BSViewdata"] },
    CharsetData { preferred_name: "", name: "INIS", names: &["iso-ir-49", "csISO49INIS"] },
    CharsetData { preferred_name: "", name: "INIS-8", names: &["iso-ir-50", "csISO50INIS8"] },
    CharsetData { preferred_name: "", name: "INIS-cyrillic", names: &["iso-ir-51", "csISO51INISCyrillic"] },
    CharsetData { preferred_name: "", name: "ISO_5427:1981", names: &["iso-ir-54", "ISO5427Cyrillic1981", "csISO54271981"] },
    CharsetData { preferred_name: "", name: "ISO_5428:1980", names: &["iso-ir-55", "csISO5428Greek"] },
    CharsetData { preferred_name: "", name: "GB_1988-80", names: &["iso-ir-57", "cn", "ISO646-CN", "csISO57GB1988"] },
    CharsetData { preferred_name: "", name: "GB_2312-80", names: &["iso-ir-58", "chinese", "csISO58GB231280"] },
    CharsetData { preferred_name: "", name: "NS_4551-2", names: &["ISO646-NO2", "iso-ir-61", "no2", "csISO61Norwegian2"] },
    CharsetData { preferred_name: "", name: "videotex-suppl", names: &["iso-ir-70", "csISO70VideotexSupp1"] },
    CharsetData { preferred_name: "", name: "PT2", names: &["iso-ir-84", "ISO646-PT2", "csISO84Portuguese2"] },
    CharsetData { preferred_name: "", name: "ES2", names: &["iso-ir-85", "ISO646-ES2", "csISO85Spanish2"] },
    CharsetData { preferred_name: "", name: "MSZ_7795.3", names: &["iso-ir-86", "ISO646-HU", "hu", "csISO86Hungarian"] },
    CharsetData { preferred_name: "", name: "JIS_C6226-1983", names: &["iso-ir-87", "x0208", "JIS_X0208-1983", "csISO87JISX0208"] },
    CharsetData { preferred_name: "", name: "greek7", names: &["iso-ir-88", "csISO88Greek7"] },
    CharsetData { preferred_name: "", name: "ASMO_449", names: &["ISO_9036", "arabic7", "iso-ir-89", "csISO89ASMO449"] },
    CharsetData { preferred_name: "", name: "iso-ir-90", names: &["csISO90"] },
    CharsetData { preferred_name: "", name: "JIS_C6229-1984-a", names: &["iso-ir-91", "jp-ocr-a", "csISO91JISC62291984a"] },
    CharsetData { preferred_name: "", name: "JIS_C6229-1984-b", names: &["iso-ir-92", "ISO646-JP-OCR-B", "jp-ocr-b", "csISO92JISC62991984b"] },
    CharsetData { preferred_name: "", name: "JIS_C6229-1984-b-add", names: &["iso-ir-93", "jp-ocr-b-add", "csISO93JIS62291984badd"] },
    CharsetData { preferred_name: "", name: "JIS_C6229-1984-hand", names: &["iso-ir-94", "jp-ocr-hand", "csISO94JIS62291984hand"] },
    CharsetData { preferred_name: "", name: "JIS_C6229-1984-hand-add", names: &["iso-ir-95", "jp-ocr-hand-add", "csISO95JIS62291984handadd"] },
    CharsetData { preferred_name: "", name: "JIS_C6229-1984-kana", names: &["iso-ir-96", "csISO96JISC62291984kana"] },
    CharsetData { preferred_name: "", name: "ISO_2033-1983", names: &["iso-ir-98", "e13b", "csISO2033"] },
    CharsetData { preferred_name: "", name: "ANSI_X3.110-1983", names: &["iso-ir-99", "CSA_T500-1983", "NAPLPS", "csISO99NAPLPS"] },
    CharsetData { preferred_name: "", name: "T.61-7bit", names: &["iso-ir-102", "csISO102T617bit"] },
    CharsetData { preferred_name: "", name: "T.61-8bit", names: &["T.61", "iso-ir-103", "csISO103T618bit"] },
    CharsetData { preferred_name: "", name: "ECMA-cyrillic", names: &["iso-ir-111", "KOI8-E", "csISO111ECMACyrillic"] },
    CharsetData { preferred_name: "", name: "CSA_Z243.4-1985-1", names: &["iso-ir-121", "ISO646-CA", "csa7-1", "csa71", "ca", "csISO121Canadian1"] },
    CharsetData { preferred_name: "", name: "CSA_Z243.4-1985-2", names: &["iso-ir-122", "ISO646-CA2", "csa7-2", "csa72", "csISO122Canadian2"] },
    CharsetData { preferred_name: "", name: "CSA_Z243.4-1985-gr", names: &["iso-ir-123", "csISO123CSAZ24341985gr"] },
    CharsetData { preferred_name: "ISO-8859-6-E", name: "ISO_8859-6-E", names: &["csISO88596E", "ISO-8859-6-E"] },
    CharsetData { preferred_name: "ISO-8859-6-I", name: "ISO_8859-6-I", names: &["csISO88596I", "ISO-8859-6-I"] },
    CharsetData { preferred_name: "", name: "T.101-G2", names: &["iso-ir-128", "csISO128T101G2"] },
    CharsetData { preferred_name: "ISO-8859-8-E", name: "ISO_8859-8-E", names: &["csISO88598E", "ISO-8859-8-E"] },
    CharsetData { preferred_name: "ISO-8859-8-I", name: "ISO_8859-8-I", names: &["csISO88598I", "ISO-8859-8-I"] },
    CharsetData { preferred_name: "", name: "CSN_369103", names: &["iso-ir-139", "csISO139CSN369103"] },
    CharsetData { preferred_name: "", name: "JUS_I.B1.002", names: &["iso-ir-141", "ISO646-YU", "js", "yu", "csISO141JUSIB1002"] },
    CharsetData { preferred_name: "", name: "IEC_P27-1", names: &["iso-ir-143", "csISO143IECP271"] },
    CharsetData { preferred_name: "", name: "JUS_I.B1.003-serb", names: &["iso-ir-146", "serbian", "csISO146Serbian"] },
    CharsetData { preferred_name: "", name: "JUS_I.B1.003-mac", names: &["macedonian", "iso-ir-147", "csISO147Macedonian"] },
    CharsetData { preferred_name: "", name: "greek-ccitt", names: &["iso-ir-150", "csISO150", "csISO150GreekCCITT"] },
    CharsetData { preferred_name: "", name: "NC_NC00-10:81", names: &["cuba", "iso-ir-151", "ISO646-CU", "csISO151Cuba"] },
    CharsetData { preferred_name: "", name: "ISO_6937-2-25", names: &["iso-ir-152", "csISO6937Add"] },
    CharsetData { preferred_name: "", name: "GOST_19768-74", names: &["ST_SEV_358-88", "iso-ir-153", "csISO153GOST1976874"] },
    CharsetData { preferred_name: "", name: "ISO_8859-supp", names: &["iso-ir-154", "latin1-2-5", "csISO8859Supp"] },
    CharsetData { preferred_name: "", name: "ISO_10367-box", names: &["iso-ir-155", "csISO10367Box"] },
    CharsetData { preferred_name: "", name: "latin-lap", names: &["lap", "iso-ir-158", "csISO158Lap"] },
    CharsetData { preferred_name: "", name: "JIS_X0212-1990", names: &["x0212", "iso-ir-159", "csISO159JISX02121990"] },
    CharsetData { preferred_name: "", name: "DS_2089", names: &["DS2089", "ISO646-DK", "dk", "csISO646Danish"] },
    CharsetData { preferred_name: "", name: "us-dk", names: &["csUSDK"] },
    CharsetData { preferred_name: "", name: "dk-us", names: &["csDKUS"] },
    CharsetData { preferred_name: "", name: "KSC5636", names: &["ISO646-KR", "csKSC5636"] },
    CharsetData { preferred_name: "", name: "UNICODE-1-1-UTF-7", names: &["csUnicode11UTF7"] },
    CharsetData { preferred_name: "", name: "ISO-2022-CN", names: &["csISO2022CN"] },
    CharsetData { preferred_name: "", name: "ISO-2022-CN-EXT", names: &["csISO2022CNEXT"] },
    CharsetData { preferred_name: "", name: "UTF-8", names: &["csUTF8"] },
    CharsetData { preferred_name: "", name: "ISO-8859-13", names: &["csISO885913"] },
    CharsetData { preferred_name: "", name: "ISO-8859-14", names: &["iso-ir-199", "ISO_8859-14:1998", "ISO_8859-14", "latin8", "iso-celtic", "l8", "csISO885914"] },
    CharsetData { preferred_name: "", name: "ISO-8859-15", names: &["ISO_8859-15", "Latin-9", "csISO885915"] },
    CharsetData { preferred_name: "", name: "ISO-8859-16", names: &["iso-ir-226", "ISO_8859-16:2001", "ISO_8859-16", "latin10", "l10", "csISO885916"] },
    CharsetData { preferred_name: "", name: "GBK", names: &["CP936", "MS936", "windows-936", "csGBK"] },
    CharsetData { preferred_name: "", name: "GB18030", names: &["csGB18030"] },
    CharsetData { preferred_name: "", name: "OSD_EBCDIC_DF04_15", names: &["csOSDEBCDICDF0415"] },
    CharsetData { preferred_name: "", name: "OSD_EBCDIC_DF03_IRV", names: &["csOSDEBCDICDF03IRV"] },
    CharsetData { preferred_name: "", name: "OSD_EBCDIC_DF04_1", names: &["csOSDEBCDICDF041"] },
    CharsetData { preferred_name: "", name: "ISO-11548-1", names: &["ISO_11548-1", "ISO_TR_11548-1", "csISO115481"] },
    CharsetData { preferred_name: "", name: "KZ-1048", names: &["STRK1048-2002", "RK1048", "csKZ1048"] },
    CharsetData { preferred_name: "", name: "ISO-10646-UCS-2", names: &["csUnicode"] },
    CharsetData { preferred_name: "", name: "ISO-10646-UCS-4", names: &["csUCS4"] },
    CharsetData { preferred_name: "", name: "ISO-10646-UCS-Basic", names: &["csUnicodeASCII"] },
    CharsetData { preferred_name: "", name: "ISO-10646-Unicode-Latin1", names: &["csUnicodeLatin1", "ISO-10646"] },
    CharsetData { preferred_name: "", name: "ISO-10646-J-1", names: &["csUnicodeJapanese"] },
    CharsetData { preferred_name: "", name: "ISO-Unicode-IBM-1261", names: &["csUnicodeIBM1261"] },
    CharsetData { preferred_name: "", name: "ISO-Unicode-IBM-1268", names: &["csUnicodeIBM1268"] },
    CharsetData { preferred_name: "", name: "ISO-Unicode-IBM-1276", names: &["csUnicodeIBM1276"] },
    CharsetData { preferred_name: "", name: "ISO-Unicode-IBM-1264", names: &["csUnicodeIBM1264"] },
    CharsetData { preferred_name: "", name: "ISO-Unicode-IBM-1265", names: &["csUnicodeIBM1265"] },
    CharsetData { preferred_name: "", name: "UNICODE-1-1", names: &["csUnicode11"] },
    CharsetData { preferred_name: "", name: "SCSU", names: &["csSCSU"] },
    CharsetData { preferred_name: "", name: "UTF-7", names: &["csUTF7"] },
    CharsetData { preferred_name: "", name: "UTF-16BE", names: &["csUTF16BE"] },
    CharsetData { preferred_name: "", name: "UTF-16LE", names: &["csUTF16LE"] },
    CharsetData { preferred_name: "", name: "UTF-16", names: &["csUTF16"] },
    CharsetData { preferred_name: "", name: "CESU-8", names: &["csCESU8", "csCESU-8"] },
    CharsetData { preferred_name: "", name: "UTF-32", names: &["csUTF32"] },
    CharsetData { preferred_name: "", name: "UTF-32BE", names: &["csUTF32BE"] },
    CharsetData { preferred_name: "", name: "UTF-32LE", names: &["csUTF32LE"] },
    CharsetData { preferred_name: "", name: "BOCU-1", names: &["csBOCU1", "csBOCU-1"] },
    CharsetData { preferred_name: "", name: "UTF-7-IMAP", names: &["csUTF7IMAP"] },
    CharsetData { preferred_name: "", name: "ISO-8859-1-Windows-3.0-Latin-1", names: &["csWindows30Latin1"] },
    CharsetData { preferred_name: "", name: "ISO-8859-1-Windows-3.1-Latin-1", names: &["csWindows31Latin1"] },
    CharsetData { preferred_name: "", name: "ISO-8859-2-Windows-Latin-2", names: &["csWindows31Latin2"] },
    CharsetData { preferred_name: "", name: "ISO-8859-9-Windows-Latin-5", names: &["csWindows31Latin5"] },
    CharsetData { preferred_name: "", name: "hp-roman8", names: &["roman8", "r8", "csHPRoman8"] },
    CharsetData { preferred_name: "", name: "Adobe-Standard-Encoding", names: &["csAdobeStandardEncoding"] },
    CharsetData { preferred_name: "", name: "Ventura-US", names: &["csVenturaUS"] },
    CharsetData { preferred_name: "", name: "Ventura-International", names: &["csVenturaInternational"] },
    CharsetData { preferred_name: "", name: "DEC-MCS", names: &["dec", "csDECMCS"] },
    CharsetData { preferred_name: "", name: "IBM850", names: &["cp850", "850", "csPC850Multilingual"] },
    CharsetData { preferred_name: "", name: "PC8-Danish-Norwegian", names: &["csPC8DanishNorwegian"] },
    CharsetData { preferred_name: "", name: "IBM862", names: &["cp862", "862", "csPC862LatinHebrew"] },
    CharsetData { preferred_name: "", name: "PC8-Turkish", names: &["csPC8Turkish"] },
    CharsetData { preferred_name: "", name: "IBM-Symbols", names: &["csIBMSymbols"] },
    CharsetData { preferred_name: "", name: "IBM-Thai", names: &["csIBMThai"] },
    CharsetData { preferred_name: "", name: "HP-Legal", names: &["csHPLegal"] },
    CharsetData { preferred_name: "", name: "HP-Pi-font", names: &["csHPPiFont"] },
    CharsetData { preferred_name: "", name: "HP-Math8", names: &["csHPMath8"] },
    CharsetData { preferred_name: "", name: "Adobe-Symbol-Encoding", names: &["csHPPSMath"] },
    CharsetData { preferred_name: "", name: "HP-DeskTop", names: &["csHPDesktop"] },
    CharsetData { preferred_name: "", name: "Ventura-Math", names: &["csVenturaMath"] },
    CharsetData { preferred_name: "", name: "Microsoft-Publishing", names: &["csMicrosoftPublishing"] },
    CharsetData { preferred_name: "", name: "Windows-31J", names: &["csWindows31J"] },
    CharsetData { preferred_name: "GB2312", name: "GB2312", names: &["csGB2312"] },
    CharsetData { preferred_name: "Big5", name: "Big5", names: &["csBig5"] },
    CharsetData { preferred_name: "", name: "macintosh", names: &["mac", "csMacintosh"] },
    CharsetData { preferred_name: "", name: "IBM037", names: &["cp037", "ebcdic-cp-us", "ebcdic-cp-ca", "ebcdic-cp-wt", "ebcdic-cp-nl", "csIBM037"] },
    CharsetData { preferred_name: "", name: "IBM038", names: &["EBCDIC-INT", "cp038", "csIBM038"] },
    CharsetData { preferred_name: "", name: "IBM273", names: &["CP273", "csIBM273"] },
    CharsetData { preferred_name: "", name: "IBM274", names: &["EBCDIC-BE", "CP274", "csIBM274"] },
    CharsetData { preferred_name: "", name: "IBM275", names: &["EBCDIC-BR", "cp275", "csIBM275"] },
    CharsetData { preferred_name: "", name: "IBM277", names: &["EBCDIC-CP-DK", "EBCDIC-CP-NO", "csIBM277"] },
    CharsetData { preferred_name: "", name: "IBM278", names: &["CP278", "ebcdic-cp-fi", "ebcdic-cp-se", "csIBM278"] },
    CharsetData { preferred_name: "", name: "IBM280", names: &["CP280", "ebcdic-cp-it", "csIBM280"] },
    CharsetData { preferred_name: "", name: "IBM281", names: &["EBCDIC-JP-E", "cp281", "csIBM281"] },
    CharsetData { preferred_name: "", name: "IBM284", names: &["CP284", "ebcdic-cp-es", "csIBM284"] },
    CharsetData { preferred_name: "", name: "IBM285", names: &["CP285", "ebcdic-cp-gb", "csIBM285"] },
    CharsetData { preferred_name: "", name: "IBM290", names: &["cp290", "EBCDIC-JP-kana", "csIBM290"] },
    CharsetData { preferred_name: "", name: "IBM297", names: &["cp297", "ebcdic-cp-fr", "csIBM297"] },
    CharsetData { preferred_name: "", name: "IBM420", names: &["cp420", "ebcdic-cp-ar1", "csIBM420"] },
    CharsetData { preferred_name: "", name: "IBM423", names: &["cp423", "ebcdic-cp-gr", "csIBM423"] },
    CharsetData { preferred_name: "", name: "IBM424", names: &["cp424", "ebcdic-cp-he", "csIBM424"] },
    CharsetData { preferred_name: "", name: "IBM437", names: &["cp437", "437", "csPC8CodePage437"] },
    CharsetData { preferred_name: "", name: "IBM500", names: &["CP500", "ebcdic-cp-be", "ebcdic-cp-ch", "csIBM500"] },
    CharsetData { preferred_name: "", name: "IBM851", names: &["cp851", "851", "csIBM851"] },
    CharsetData { preferred_name: "", name: "IBM852", names: &["cp852", "852", "csPCp852"] },
    CharsetData { preferred_name: "", name: "IBM855", names: &["cp855", "855", "csIBM855"] },
    CharsetData { preferred_name: "", name: "IBM857", names: &["cp857", "857", "csIBM857"] },
    CharsetData { preferred_name: "", name: "IBM860", names: &["cp860", "860", "csIBM860"] },
    CharsetData { preferred_name: "", name: "IBM861", names: &["cp861", "861", "cp-is", "csIBM861"] },
    CharsetData { preferred_name: "", name: "IBM863", names: &["cp863", "863", "csIBM863"] },
    CharsetData { preferred_name: "", name: "IBM864", names: &["cp864", "csIBM864"] },
    CharsetData { preferred_name: "", name: "IBM865", names: &["cp865", "865", "csIBM865"] },
    CharsetData { preferred_name: "", name: "IBM868", names: &["CP868", "cp-ar", "csIBM868"] },
    CharsetData { preferred_name: "", name: "IBM869", names: &["cp869", "869", "cp-gr", "csIBM869"] },
    CharsetData { preferred_name: "", name: "IBM870", names: &["CP870", "ebcdic-cp-roece", "ebcdic-cp-yu", "csIBM870"] },
    CharsetData { preferred_name: "", name: "IBM871", names: &["CP871", "ebcdic-cp-is", "csIBM871"] },
    CharsetData { preferred_name: "", name: "IBM880", names: &["cp880", "EBCDIC-Cyrillic", "csIBM880"] },
    CharsetData { preferred_name: "", name: "IBM891", names: &["cp891", "csIBM891"] },
    CharsetData { preferred_name: "", name: "IBM903", names: &["cp903", "csIBM903"] },
    CharsetData { preferred_name: "", name: "IBM904", names: &["cp904", "904", "csIBBM904"] },
    CharsetData { preferred_name: "", name: "IBM905", names: &["CP905", "ebcdic-cp-tr", "csIBM905"] },
    CharsetData { preferred_name: "", name: "IBM918", names: &["CP918", "ebcdic-cp-ar2", "csIBM918"] },
    CharsetData { preferred_name: "", name: "IBM1026", names: &["CP1026", "csIBM1026"] },
    CharsetData { preferred_name: "", name: "EBCDIC-AT-DE", names: &["csIBMEBCDICATDE"] },
    CharsetData { preferred_name: "", name: "EBCDIC-AT-DE-A", names: &["csEBCDICATDEA"] },
    CharsetData { preferred_name: "", name: "EBCDIC-CA-FR", names: &["csEBCDICCAFR"] },
    CharsetData { preferred_name: "", name: "EBCDIC-DK-NO", names: &["csEBCDICDKNO"] },
    CharsetData { preferred_name: "", name: "EBCDIC-DK-NO-A", names: &["csEBCDICDKNOA"] },
    CharsetData { preferred_name: "", name: "EBCDIC-FI-SE", names: &["csEBCDICFISE"] },
    CharsetData { preferred_name: "", name: "EBCDIC-FI-SE-A", names: &["csEBCDICFISEA"] },
    CharsetData { preferred_name: "", name: "EBCDIC-FR", names: &["csEBCDICFR"] },
    CharsetData { preferred_name: "", name: "EBCDIC-IT", names: &["csEBCDICIT"] },
    CharsetData { preferred_name: "", name: "EBCDIC-PT", names: &["csEBCDICPT"] },
    CharsetData { preferred_name: "", name: "EBCDIC-ES", names: &["csEBCDICES"] },
    CharsetData { preferred_name: "", name: "EBCDIC-ES-A", names: &["csEBCDICESA"] },
    CharsetData { preferred_name: "", name: "EBCDIC-ES-S", names: &["csEBCDICESS"] },
    CharsetData { preferred_name: "", name: "EBCDIC-UK", names: &["csEBCDICUK"] },
    CharsetData { preferred_name: "", name: "EBCDIC-US", names: &["csEBCDICUS"] },
    CharsetData { preferred_name: "", name: "UNKNOWN-8BIT", names: &["csUnknown8BiT"] },
    CharsetData { preferred_name: "", name: "MNEMONIC", names: &["csMnemonic"] },
    CharsetData { preferred_name: "", name: "MNEM", names: &["csMnem"] },
    CharsetData { preferred_name: "", name: "VISCII", names: &["csVISCII"] },
    CharsetData { preferred_name: "", name: "VIQR", names: &["csVIQR"] },
    CharsetData { preferred_name: "KOI8-R", name: "KOI8-R", names: &["csKOI8R"] },
    CharsetData { preferred_name: "", name: "HZ-GB-2312", names: &[""] },
    CharsetData { preferred_name: "", name: "IBM866", names: &["cp866", "866", "csIBM866"] },
    CharsetData { preferred_name: "", name: "IBM775", names: &["cp775", "csPC775Baltic"] },
    CharsetData { preferred_name: "", name: "KOI8-U", names: &["csKOI8U"] },
    CharsetData { preferred_name: "", name: "IBM00858", names: &["CCSID00858", "CP00858", "PC-Multilingual-850+euro", "csIBM00858"] },
    CharsetData { preferred_name: "", name: "IBM00924", names: &["CCSID00924", "CP00924", "ebcdic-Latin9--euro", "csIBM00924"] },
    CharsetData { preferred_name: "", name: "IBM01140", names: &["CCSID01140", "CP01140", "ebcdic-us-37+euro", "csIBM01140"] },
    CharsetData { preferred_name: "", name: "IBM01141", names: &["CCSID01141", "CP01141", "ebcdic-de-273+euro", "csIBM01141"] },
    CharsetData { preferred_name: "", name: "IBM01142", names: &["CCSID01142", "CP01142", "ebcdic-dk-277+euro", "ebcdic-no-277+euro", "csIBM01142"] },
    CharsetData { preferred_name: "", name: "IBM01143", names: &["CCSID01143", "CP01143", "ebcdic-fi-278+euro", "ebcdic-se-278+euro", "csIBM01143"] },
    CharsetData { preferred_name: "", name: "IBM01144", names: &["CCSID01144", "CP01144", "ebcdic-it-280+euro", "csIBM01144"] },
    CharsetData { preferred_name: "", name: "IBM01145", names: &["CCSID01145", "CP01145", "ebcdic-es-284+euro", "csIBM01145"] },
    CharsetData { preferred_name: "", name: "IBM01146", names: &["CCSID01146", "CP01146", "ebcdic-gb-285+euro", "csIBM01146"] },
    CharsetData { preferred_name: "", name: "IBM01147", names: &["CCSID01147", "CP01147", "ebcdic-fr-297+euro", "csIBM01147"] },
    CharsetData { preferred_name: "", name: "IBM01148", names: &["CCSID01148", "CP01148", "ebcdic-international-500+euro", "csIBM01148"] },
    CharsetData { preferred_name: "", name: "IBM01149", names: &["CCSID01149", "CP01149", "ebcdic-is-871+euro", "csIBM01149"] },
    CharsetData { preferred_name: "", name: "Big5-HKSCS", names: &["csBig5HKSCS"] },
    CharsetData { preferred_name: "", name: "IBM1047", names: &["IBM-1047", "csIBM1047"] },
    CharsetData { preferred_name: "", name: "PTCP154", names: &["csPTCP154", "PT154", "CP154", "Cyrillic-Asian"] },
    CharsetData { preferred_name: "", name: "Amiga-1251", names: &["Ami1251", "Amiga1251", "Ami-1251", "csAmiga1251"] },
    CharsetData { preferred_name: "", name: "KOI7-switched", names: &["csKOI7switched"] },
    CharsetData { preferred_name: "", name: "BRF", names: &["csBRF"] },
    CharsetData { preferred_name: "", name: "TSCII", names: &["csTSCII"] },
    CharsetData { preferred_name: "", name: "CP51932", names: &["csCP51932"] },
    CharsetData { preferred_name: "", name: "windows-874", names: &["cswindows874"] },
    CharsetData { preferred_name: "", name: "windows-1250", names: &["cswindows1250"] },
    CharsetData { preferred_name: "", name: "windows-1251", names: &["cswindows1251"] },
    CharsetData { preferred_name: "", name: "windows-1252", names: &["cswindows1252"] },
    CharsetData { preferred_name: "", name: "windows-1253", names: &["cswindows1253"] },
    CharsetData { preferred_name: "", name: "windows-1254", names: &["cswindows1254"] },
    CharsetData { preferred_name: "", name: "windows-1255", names: &["cswindows1255"] },
    CharsetData { preferred_name: "", name: "windows-1256", names: &["cswindows1256"] },
    CharsetData { preferred_name: "", name: "windows-1257", names: &["cswindows1257"] },
    CharsetData { preferred_name: "", name: "windows-1258", names: &["cswindows1258"] },
    CharsetData { preferred_name: "", name: "TIS-620", names: &["csTIS620", "ISO-8859-11"] },
    CharsetData { preferred_name: "", name: "CP50220", names: &["csCP50220"] }
];

#[derive(Debug,PartialEq)]
pub(crate)  struct CharsetDataEntry {
    pub(crate) preferred_name: String,
    pub(crate) name: String,
    pub(crate) names: Vec<String>,
}

impl convert::From<CharsetData> for CharsetDataEntry {
    fn from(d: CharsetData) -> Self {
        Self {
            preferred_name: d.preferred_name.to_owned(),
            name: d.name.to_owned(),
            names: d.names.iter().map(|n| n.to_string()).collect::<Vec<String>>(),
        }
    }
}

impl convert::From<&CharsetData> for CharsetDataEntry {
    fn from(d: &CharsetData) -> Self {
        Self {
            preferred_name: d.preferred_name.to_owned(),
            name: d.name.to_owned(),
            names: d.names.iter().map(|n| n.to_string()).collect::<Vec<String>>(),
        }
    }
}

impl default::Default for CharsetDataEntry {
    fn default() -> Self {
        Self {
            preferred_name: "".to_owned(),
            name: "".to_owned(),
            names: vec![],
        }
    }
}

